# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

version: '3.4'

services:
  surveybackendwebapi:
    image: surveybackendwebapi
    build:
      context: .
      dockerfile: survey-backend.webapi/Dockerfile
    ports:
      - 5216:5216
